function MeFancyQuiver3(xdata1, ydata1, zdata1, udata1, vdata1, wdata1);
%CREATEFIGURE(xdata1, ydata1, zdata1)
%  XDATA1:  surface xdata
%  YDATA1:  surface ydata
%  ZDATA1:  surface zdata

%  Auto-generated by MATLAB on 16-Sep-2019 14:11:24

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create surf
quiver3(xdata1,ydata1,zdata1,udata1, vdata1,wdata1,'Parent',axes1,'Color','black');

% Create ylabel
ylabel('$y$ / pc','FontSize',24,'Interpreter','latex');

% Create xlabel
xlabel('$x$ / pc','FontSize',24,'Interpreter','latex');

zlabel('$z$ / pc','FontSize',24,'Interpreter','latex');

grid(axes1,'on');
axis(axes1,'tight');
% Set the remaining axes properties
set(axes1,'DataAspectRatio',[1 1 1],'FontSize',20);


